#version 450

#define WORKGROUP_SIZE 32
layout (
local_size_x = WORKGROUP_SIZE, // outputs dimension
local_size_y = WORKGROUP_SIZE// batches dimension
) in;

layout(push_constant) uniform Sizes {
    uint K; // number of columns in I / W
    uint M; // number of rows in W (outputs)
    uint N; // number of rows in I (batch size)
} sizes;

// Input matrix I (N x K)
layout(binding = 0) readonly buffer InputBuffer {
    float I[];
};

// Weight matrix W (M x K)
layout(binding = 1) readonly buffer WeightBuffer {
    float W[];
};

// Output matrix O (N x M)
layout(binding = 2) writeonly buffer OutputBuffer {
    float O[];
};

shared float tileI[WORKGROUP_SIZE][WORKGROUP_SIZE];
shared float tileW[WORKGROUP_SIZE][WORKGROUP_SIZE];

void main() {
    uint row = gl_GlobalInvocationID.y;
    uint col = gl_GlobalInvocationID.x;

    float sum = 0.0;

    for (uint t = 0; t < sizes.K; t += WORKGROUP_SIZE) {
        uint lx = gl_LocalInvocationID.x;
        uint ly = gl_LocalInvocationID.y;

        tileI[ly][lx] = (t + lx < sizes.K) ? I[row * sizes.K + (t + lx)] : 0.0;
        tileW[ly][lx] = (t + ly < sizes.K) ? W[col * sizes.K + (t + ly)] : 0.0;

        barrier();

        for (uint k = 0; k < WORKGROUP_SIZE; k++) {
            sum += tileI[ly][k] * tileW[k][lx];
        }

        barrier();
    }

    if (row < sizes.N && col < sizes.M) {
        O[row * sizes.M + col] = sum;
    }
}
