#version 450

#define WORKGROUP_SIZE 32
layout (
local_size_x = WORKGROUP_SIZE, // outputs dimension
local_size_y = WORKGROUP_SIZE// batches dimension
) in;

layout (binding = 0) buffer inputBuffer {
    float vInput[];
};

layout (binding = 1) buffer weightsBuffer {
    float mWeights[];
};

layout (binding = 2) buffer outputBuffer {
    float vOutput[];
};

layout (push_constant) uniform Params {
    int inputSize;
    int outputSize;
    int batchSize;
};

float getInput(uint b, uint x) {
    return vInput[b * inputSize + x];
}

float getWeight(uint x, uint y) {
    return mWeights[x + y * inputSize];
}

void setOutput(uint b, uint y, float v) {
    vOutput[b * outputSize + y] = v;
}

void addOutput(uint b, uint y, float v) {
    vOutput[b * outputSize + y] += v;
}

// Shared memory tiles
shared float Asub[WORKGROUP_SIZE][WORKGROUP_SIZE];
shared float Bsub[WORKGROUP_SIZE][WORKGROUP_SIZE];

void main() {
    uint b = gl_GlobalInvocationID.y;
    uint y = gl_GlobalInvocationID.x;
    if (b >= batchSize || y >= outputSize) return;

    float acc = 0.0;
    for (uint k0 = 0; k0 < inputSize; k0 += WORKGROUP_SIZE) {
        uint lb = gl_LocalInvocationID.y;
        uint ly = gl_LocalInvocationID.x;

        Asub[lb][ly] = ((k0 + ly) < inputSize)
            ? getInput(b, k0 + ly)
            : 0.0;

        Bsub[lb][ly] = ((k0 + lb) < inputSize)
            ? getWeight(k0 + lb, y)
            : 0.0;

        barrier();

        for (uint k = 0; k < WORKGROUP_SIZE; k++) {
            acc += Asub[lb][k] * Bsub[k][ly];
        }

        barrier();
    }
    setOutput(b, y, acc);
}
